"use client";
import {useEffect,useState} from 'react';
type Batch={batch_name?:string;detail?:string;can_stop?:boolean;manual?:boolean;ongoing_policy?:{enabled:boolean;new_companies_per_weekday:number;followup_after_days:number};active:boolean;status:string;limit:number;planned:number;sent:number;verified:number;skipped:number;followups:boolean;bounces:number;auto_replies:number;human_replies:number;stop_requested:boolean;validation_policy:string};
export default function Campaign(){
 const [batch,setBatch]=useState<Batch|null>(null),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;const load=async()=>{try{const r=await fetch('/api/campaign',{cache:'no-store'});if(!r.ok)throw Error('Campaign status unavailable');const data=await r.json();if(!cancelled){setBatch(data);setError('')}}catch(e){if(!cancelled)setError(String(e))}};load();const timer=setInterval(load,5000);return()=>{cancelled=true;clearInterval(timer)}},[]);
 async function stop(){const r=await fetch('/api/campaign/stop',{method:'POST'});if(r.ok)setBatch(b=>b?{...b,stop_requested:true}:b);else setError('Could not stop the batch. Please retry.');}
 async function pausePolicy(){const r=await fetch('/api/outreach-policy',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:false})});if(r.ok)setBatch(b=>b?{...b,ongoing_policy:{...b.ongoing_policy!,enabled:false}}:b);else setError('Could not pause outreach. Please retry.');}
 if(error)return <p className="review-issue">{error}</p>;
 if(!batch?.active)return null;
 return <section className="panel" style={{marginBottom:24}} aria-live="polite"><div className="eyebrow">{batch.batch_name||"September 24 Rocklin outreach"}</div><h2>{batch.sent} emails sent · {['running','sending'].includes(batch.status)?'live batch in progress':'batch '+batch.status}</h2><p>{batch.verified} verified in Gmail Sent. {batch.planned} contacts in this batch · daily ceiling {batch.limit}, including other sends today.</p><p>{batch.ongoing_policy?.enabled?"Ongoing outreach: up to 10 new greater Sacramento companies each weekday at 9 AM Pacific. One personalized follow-up after 7 days, only without a response. Total ceiling: 25 emails per day.":"Recurring outreach is paused. A separately authorized one-time batch may still run."}</p>{batch.ongoing_policy?.enabled&&<button className="secondary" onClick={pausePolicy}>Pause ongoing outreach</button>}<p className="muted">{batch.validation_policy}</p>{batch.status==='halted'&&<p className="review-issue">{batch.detail}</p>}{batch.skipped>0&&<p>{batch.skipped} contacts skipped.</p>}{(batch.can_stop??batch.status==='running')&&<button className="secondary" onClick={stop} disabled={batch.stop_requested}>{batch.stop_requested?'Stopping before the next email…':'Stop this batch'}</button>}</section>
}
