"""Generate TypeScript + runtime JSON Schema from private Pydantic read contracts.

No database, secrets, OpenAPI endpoint or provider call is needed. --check is a CI gate.
"""
import json
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'backend'))
from app.ui_contracts import CONTRACTS

def ts(schema):
    if '$ref' in schema: return schema['$ref'].split('/')[-1]
    if 'enum' in schema: return ' | '.join(json.dumps(x) for x in schema['enum'])
    if 'anyOf' in schema: return ' | '.join(ts(x) for x in schema['anyOf'])
    kind = schema.get('type')
    if kind == 'array': return '(' + ts(schema['items']) + ')[]'
    if kind == 'object':
        if 'properties' in schema:
            # Defaults are normalized by response_model at the private API boundary.
            return '{\n' + '\n'.join('  ' + json.dumps(k) + ': ' + ts(v) + ';' for k,v in schema['properties'].items()) + '\n}'
        additional = schema.get('additionalProperties')
        return 'Record<string, ' + (ts(additional) if isinstance(additional,dict) else 'unknown') + '>'
    return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(kind,'unknown')

def artifacts():
    definitions = {}
    for model in CONTRACTS:
        schema = model.model_json_schema(mode='serialization')
        definitions.update(schema.pop('$defs', {}))
        definitions[model.__name__] = schema
    # All view fields are present after FastAPI response serialization, including defaults.
    for schema in definitions.values():
        if 'properties' in schema: schema['required'] = list(schema['properties'])
    types = '// GENERATED by scripts/frontend_contracts.py. Do not edit.\n'
    types += '\n\n'.join('export type '+name+' = '+ts(schema)+';' for name,schema in sorted(definitions.items()))+'\n'
    return {'contracts.ts': types, 'contracts.schema.json': json.dumps({'$defs':definitions},indent=2)+'\n'}

if __name__ == '__main__':
    target = ROOT / 'frontend/lib'
    for name, content in artifacts().items():
        path = target / name
        if '--check' in sys.argv:
            if not path.exists() or path.read_text()!=content: raise SystemExit('Stale frontend contract: '+name)
        else: path.write_text(content)
