// GENERATED by scripts/frontend_contracts.py. Do not edit.
export type CampaignView = {
  "active": boolean;
  "batch_name": string;
  "status": string;
  "detail": string;
  "can_stop": boolean;
  "stop_requested": boolean;
  "limit": number;
  "planned": number;
  "sent": number;
  "verified": number;
  "skipped": number;
  "validation_policy": string;
  "outreach_ids": (string)[];
  "ongoing_policy": PolicyView;
};

export type CompanyDetail = {
  "id": string;
  "name": string;
  "domain": string;
  "website": string;
  "industry": string;
  "distance_miles": number | null;
  "description": string;
  "source": string;
  "research": Record<string, unknown>;
  "score": number;
  "score_factors": Record<string, number>;
  "stage": string;
  "demo": boolean;
  "created_at": string;
  "researched_at": string | null;
  "contacts": (ContactView)[];
  "evidence": (EvidenceView)[];
  "events": (EventView)[];
};

export type CompanyView = {
  "id": string;
  "name": string;
  "domain": string;
  "website": string;
  "industry": string;
  "distance_miles": number | null;
  "description": string;
  "source": string;
  "research": Record<string, unknown>;
  "score": number;
  "score_factors": Record<string, number>;
  "stage": string;
  "demo": boolean;
  "created_at": string;
  "researched_at": string | null;
};

export type ConnectionView = {
  "status": string;
  "email": string;
  "connected": boolean;
};

export type ContactView = {
  "id": string;
  "company_id": string;
  "email": string;
  "name": string;
  "title": string;
  "source": string;
  "validation": string;
  "validated_at": string | null;
};

export type DetectorView = {
  "provider": string;
  "ai_probability": number | null;
  "result": string;
  "checked_at": string;
  "report_url": string | null;
};

export type EmlView = {
  "filename": string;
  "content": string;
};

export type EventView = {
  "id": string;
  "company_id": string;
  "kind": string;
  "detail": string;
  "source_id": string;
  "created_at": string;
};

export type EvidenceView = {
  "id": string;
  "company_id": string;
  "fact": string;
  "quote": string;
  "url": string;
  "category": string;
  "fetched_at": string;
};

export type InboxView = {
  "enabled": boolean;
  "needs_attention": number;
  "responses": (ReplyView)[];
  "sync": SyncView;
};

export type MailboxDraftView = {
  "status": string;
  "to": string;
  "at": string | null;
};

export type MessageState = "draft" | "approved" | "rejected" | "cancelled" | "sending" | "sent" | "unknown" | "failed" | "demo";

export type MetricsView = {
  "companies": number;
  "sent": number;
  "replies": number;
  "interviews": number;
  "offers": number;
  "response_rate": number;
  "interview_rate": number;
  "conversion_rate": number;
  "sent_today": number;
  "learning": (Record<string, unknown>)[];
};

export type OutreachEdit = {
  "subject": string;
  "body": string;
};

export type OutreachView = {
  "id": string;
  "company_id": string;
  "contact_id": string;
  "sequence": number;
  "subject": string;
  "body": string;
  "evidence_ids": (string)[];
  "review": ReviewView;
  "strategy": string;
  "status": MessageState;
  "due_at": string;
  "sent_at": string | null;
  "provider_id": string;
  "thread_id": string;
  "message_id": string;
  "attempts": number;
  "created_at": string;
};

export type PacketView = {
  "id": string;
  "company": string;
  "subject": string;
  "body": string;
  "evidence": string;
  "fictional": boolean;
  "draft_hash": string;
  "status": string;
  "updated_at": string;
  "style": StyleView;
  "detector": DetectorView | null;
  "signoff": Record<string, unknown> | null;
  "mailbox_draft": MailboxDraftView | null;
  "history": (Record<string, unknown>)[];
};

export type PolicyView = {
  "enabled": boolean;
  "new_companies_per_weekday": number | null;
  "followup_after_days": number | null;
};

export type ProfileInput = {
  "name": string;
  "email": string;
  "grade": string;
  "location": string;
  "resume": string;
  "linkedin_url": string;
  "portfolio_links": (string)[];
  "projects": (string)[];
  "awards": (string)[];
  "skills": (string)[];
  "interests": (string)[];
  "cover_letter_snippets": (string)[];
  "background": string;
  "voice_notes": string;
  "writing_samples": (string)[];
  "verified": boolean;
};

export type ReplyView = {
  "id": string;
  "company_id": string;
  "company": string;
  "kind": string;
  "sender": string;
  "subject": string;
  "preview": string;
  "received_at": string;
  "handled": boolean;
  "gmail_url": string;
};

export type ReviewView = {
  "passed": boolean;
  "personalization_score": number | null;
  "issues": (string)[];
  "profile_hash": string;
  "grounded": boolean | null;
  "names_correct": boolean | null;
  "claims_supported": boolean | null;
};

export type SelfTestView = {
  "status": string;
  "to": string;
};

export type SettingsView = {
  "manual_mode": boolean;
  "dry_run": boolean;
  "daily_send_limit": number;
  "auto_approve": boolean;
  "max_pages": number;
  "research_seconds": number;
  "mail_provider": string;
  "mail_connected": boolean;
  "demo_allowed": boolean;
  "integrations": Record<string, boolean>;
  "automation": Record<string, unknown>;
};

export type StyleView = {
  "words": number;
  "generic_phrases": (string)[];
  "long_sentences": number;
  "has_question": boolean;
  "note": string;
};

export type SyncView = {
  "status": string;
  "last_success": string | null;
  "error": string | null;
};
